export const emojiUrl = "https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/"
export const emojiMap = {
  "/::)": "0.gif",
  "/::~": "1.gif",
  "/::B": "2.gif",
  "/::|": "3.gif",
  "/:8-)": "4.gif",
  "/::<": "5.gif",
  "/::$": "6.gif",
  "/::X": "7.gif",
  "/::Z": "8.gif",
  "/::'(": "9.gif",
  "/::-|": "10.gif",
  "/::@": "11.gif",
  "/::P": "12.gif",
  "/::D": "13.gif",
  "/::O": "14.gif",
  "/::(": "15.gif",
  "/::+": "16.gif",
  "/:--b": "17.gif",
  "/::Q": "18.gif",
  "/::T": "19.gif",
  "/:,@P": "20.gif",
  "/:,@-D": "21.gif",
  "/::d": "22.gif",
  "/:,@o": "23.gif",
  "/::g": "24.gif",
  "/:|-)": "25.gif",
  "/::!": "26.gif",
  "/::L": "27.gif",
  "/::>": "28.gif",
  "/::,@": "29.gif",
  "/:,@f": "30.gif",
  "/::-S": "31.gif",
  "/:?": "32.gif",
  "/:,@x": "33.gif",
  "/:,@@": "34.gif",
  "/::8": "35.gif",
  "/:,@!": "36.gif",
  "/:!!!": "37.gif",
  "/:xx": "38.gif",
  "/:bye": "39.gif",
  "/:wipe": "40.gif",
  "/:dig": "41.gif",
  "/:handclap": "42.gif",
  "/:&-(": "43.gif",
  "/:B-)": "44.gif",
  "/:<@": "45.gif",
  "/:@>": "46.gif",
  "/::-O": "47.gif",
  "/:>-|": "48.gif",
  "/:P-(": "49.gif",
  "/::'|": "50.gif",
  "/:X-)": "51.gif",
  "/::*": "52.gif",
  "/:@x": "53.gif",
  "/:8*": "54.gif",
  "/:pd": "55.gif",
  "/:<W>": "56.gif",
  "/:beer": "57.gif",
  "/:basketb": "58.gif",
  "/:oo": "59.gif",
  "/:coffee": "60.gif",
  "/:eat": "61.gif",
  "/:pig": "62.gif",
  "/:rose": "63.gif",
  "/:fade": "64.gif",
  "/:showlove": "65.gif",
  "/:heart": "66.gif",
  "/:break": "67.gif",
  "/:cake": "68.gif",
  "/:li": "69.gif",
  "/:bome": "70.gif",
  "/:kn": "71.gif",
  "/:footb": "72.gif",
  "/:ladybug": "73.gif",
  "/:shit": "74.gif",
  "/:moon": "75.gif",
  "/:sun": "76.gif",
  "/:gift": "77.gif",
  "/:hug": "78.gif",
  "/:strong": "79.gif",
  "/:weak": "80.gif",
  "/:share": "81.gif",
  "/:v": "82.gif",
  "/:@)": "83.gif",
  "/:jj": "84.gif",
  "/:@@": "85.gif",
  "/:bad": "86.gif",
  "/:lvu": "87.gif",
  "/:no": "88.gif",
  "/:ok": "89.gif",
  "/:love": "90.gif",
  "/:<L>": "91.gif",
  "/:jump": "92.gif",
  "/:shake": "93.gif",
  "/:<O>": "94.gif",
  "/:circle": "95.gif",
  "/:kotow": "96.gif",
  "/:turn": "97.gif",
  "/:skip": "98.gif",
  "/:oY": "99.gif"
}
const emojiName = [
  "/::)",
  "/::~",
  "/::B",
  "/::|",
  "/:8-)",
  "/::<",
  "/::$",
  "/::X",
  "/::Z",
  "/::'(",
  "/::-|",
  "/::@",
  "/::P",
  "/::D",
  "/::O",
  "/::(",
  "/::+",
  "/:--b",
  "/::Q",
  "/::T",
  "/:,@P",
  "/:,@-D",
  "/::d",
  "/:,@o",
  "/::g",
  "/:|-)",
  "/::!",
  "/::L",
  "/::>",
  "/::,@",
  "/:,@f",
  "/::-S",
  "/:?",
  "/:,@x",
  "/:,@@",
  "/::8",
  "/:,@!",
  "/:!!!",
  "/:xx",
  "/:bye",
  "/:wipe",
  "/:dig",
  "/:handclap",
  "/:&-(",
  "/:B-)",
  "/:<@",
  "/:@>",
  "/::-O",
  "/:>-|",
  "/:P-(",
  "/::'|",
  "/:X-)",
  "/::*",
  "/:@x",
  "/:8*",
  "/:pd",
  "/:<W>",
  "/:beer",
  "/:basketb",
  "/:oo",
  "/:coffee",
  "/:eat",
  "/:pig",
  "/:rose",
  "/:fade",
  "/:showlove",
  "/:heart",
  "/:break",
  "/:cake",
  "/:li",
  "/:bome",
  "/:kn",
  "/:footb",
  "/:ladybug",
  "/:shit",
  "/:moon",
  "/:sun",
  "/:gift",
  "/:hug",
  "/:strong",
  "/:weak",
  "/:share",
  "/:v",
  "/:@)",
  "/:jj",
  "/:@@",
  "/:bad",
  "/:lvu",
  "/:no",
  "/:ok",
  "/:love",
  "/:<L>",
  "/:jump",
  "/:shake",
  "/:<O>",
  "/:circle",
  "/:kotow",
  "/:turn",
  "/:skip",
  "/:oY"
]